# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            mikebabineau
tagline:          engineer
description:      "I don't always blog, but when I do, it's probably here."
url:              http://blog.mikebabineau.com

author:
  name:           Mike Babineau
  email:          michael.babineau@gmail.com
  github:         mbabineau
  twitter:        mikebabineau
  url:            http://mikebabineau.com

paginate:         5

# Custom vars
links:
    github:       https://github.com/mbabineau
    linkedin:     https://linkedin.com/in/mbabineau

